server:
  port: 8090
spring:
  management.endpoints.web.exposure.include:
    - "*"
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true
    hibernate.ddl-auto: 'create-drop'
    database-platform: org.hibernate.dialect.PostgresPlusDialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgresuser
    password: postgrespw
dataset.location: ".\\src\\main\\resources\\DataSets"